export const STR = {
  title: "ASTERIA",
  subtitle: "Wish of the Fallen Star",
  pressStart: "Press SPACE / tap to begin the hunt",
  intro: "Her island vanished. The world woke in her temples.|Every elementalist hunts Asteria - she grants any wish.|You chase too. You cannot remember why.",
  controls: "A/D: run  Space: jump  J: cast  K: blink  I / hold S: ward  Q: switch  L: fusion",
  controlsTouch: "Left side: move    Right side: jump / cast / dash",
  heat: "TRAIL",
  hpLabel: "VITALITY",
  elFire: "FIRE", elLightning: "LIGHTNING", elGravity: "GRAVITY",
  forbidden: "FORBIDDEN ELEMENT LEARNED",
  pickupLightning: "LIGHTNING - an element no elementalist may wield. But you can.",
  pickupGravity: "GRAVITY - Saturn's bind answers a name you forgot.",
  shard: "+TRAIL",
  rival1Name: "PYRRHOS OF THE MARS COURT",
  rival1Wish: "\"My legion burned. She will return them. Stand aside, anomaly.\"",
  rival2Name: "SELENE OF THE MOON TIDE",
  rival2Wish: "\"I only want one voice back. Why do YOU chase her? You don't even know.\"",
  rival3Name: "KESTREL OF THE MERCURY WINDS",
  rival3Wish: "\"Her wish is worth every coin in the world. Yours is worth nothing - it's blank.\"",
  rivalIntercept: "A RIVAL INTERCEPTS THE TRAIL",
  echoAbsorbed: "ECHO ABSORBED",
  echo1: "War-fire echo of Agni taken. The trail burns brighter. (+TRAIL)",
  echo2: "Tide-memory echo of Yemoja taken. Something almost surfaces... (+TRAIL)",
  echo3: "Storm-step echo of Raijin taken. The nexus is close. (+TRAIL)",
  weakHint: "Its guard breaks under the right element.",
  trailCold: "THE TRAIL WENT COLD",
  trailColdSub: "Asteria slipped away. The pack runs on without you.",
  fell: "THE VOID CLAIMS YOU",
  fellSub: "Your wish, whatever it was, stays forgotten.",
  slain: "STRUCK DOWN ON THE TRAIL",
  slainSub: "The other hunters do not look back.",
  retry: "Press SPACE / tap to chase again",
  pause: "PAUSED - tap or press P",
  nexusNear: "THE NEXUS SHRINE - SHE WAS SEEN HERE",
  fusionReady: "FUSION ART READY - hold L / FUSE",
  fusionLabel: "FUSION",
  fusionFire: "WAR STORM",
  fusionLightning: "STARFALL VERDICT",
  fusionGravity: "THE NAME THAT ESCAPES",
  fusionUsed: "echoes spent. The forbidden answers.",
  waystation: "ORACLE SANCTUARY - the hunt pauses here. No rules zone.",
  oracleGreet: "\"Anomaly. Even blank wishes cast shadows. Trade, rest, then run.\"",
  altarVit: "ALTAR OF VESSELS",
  altarVitDesc: "3 shards: restore vitality",
  altarFuse: "ALTAR OF NAMES",
  altarFuseDesc: "4 shards: fill fusion meter",
  altarBuy: "stand close + press J / CAST to trade",
  altarPoor: "not enough shards",
  shardCount: "SHARDS",
  guardianName: "THE FIRST HUNTER",
  guardianWish: "\"I reached her first, once. My wish was to guard her forever. Yours ends here.\"",
  guardianPhase: "ITS AURA SHIFTS - the old weakness no longer bites",
  bossWarn: "SOMETHING ANCIENT BLOCKS THE SHRINE",
  fragGet: "MEMORY FRAGMENT RESTORED",
  fragCount: "FRAGMENTS",
  boon1: "BOON REMEMBERED: a sixth vessel of vitality",
  boon2: "BOON REMEMBERED: the dash answers faster",
  boon3: "BOON REMEMBERED: you wake with a name half-spoken (fusion +50%)",
  metaLine: "memory fragments restored: ",
  forgeTitle: "CHOOSE YOUR CLOAK",
  forgeSub: "each cloak carries a different discipline",
  forgeHint: "A/D or arrows to browse - SPACE / tap to don it",
  cloakEmber: "EMBER CLOAK",
  cloakEmberDesc: "War-fire discipline: +30% spell damage, fusion charges faster",
  cloakTide: "TIDE CLOAK",
  cloakTideDesc: "Moon-tide discipline: stronger ward that reflects shots back",
  cloakGilded: "GILDED CLOAK",
  cloakGildedDesc: "Mercury discipline: swifter stride, shards worth double trail",
  cloakUmbral: "UMBRAL CLOAK",
  cloakUmbralDesc: "Void discipline: longer blink, longer grace after it",
  cloakVerdant: "VERDANT CLOAK",
  cloakVerdantDesc: "Gaia discipline: a deep ward reserve and a heavier strike, at a steadier pace",
  cloakTempest: "TEMPEST CLOAK",
  cloakTempestDesc: "Storm discipline: fusion gathers swiftly and your stride quickens",
  cloakAmethyst: "AMETHYST CLOAK",
  cloakAmethystDesc: "Mystic discipline: a longer blink and shards worth double trail",
  cloakSanguine: "SANGUINE CLOAK",
  cloakSanguineDesc: "Blood discipline: a punishing strike, but a thinner guard",
  wardLabel: "WARD",
  wardBroken: "WARD SHATTERED",
  blinkName: "BLINK STEP",
  reflected: "reflected!",
  escape1: "You lunge - and catch only stardust.",
  escape2: "\"Better. You were a breath behind me this time. Keep that wish unwritten a little longer.\"",
  escape3: "She is gone. A memory fragment glitters where she stood.",
  escapeTitle: "SHE SLIPS AWAY AGAIN",
  closeCalls: "CLOSE CALLS",
  controlsForge: "controls reminder: I or hold S: ward    K: blink    L: fusion",
};
